### PR TITLE
Patch 1-add UHS500

### PR DESCRIPTION
**Pull request by nyok92**
ADD UHS500 MODEL to this module.
I hope i didn't not forgot anything :)

### CODE REVIEW

**Comment by krocheck** [comment]
Can you please explain the port change.  Will the break existing users for the older cameras?

**Comment by nyok92** [comment]
This is the default port for UHS500.
Actually it is the factory default recieve port bit can ne changed manually.
On HS50 it is a fixed factory value of 60040.
And on hs410 it's 60020.
I will make some changes on this.

**Comment by nyok92** [comment]
I will let it to the original port 60040 because i'not very skilled on javascript. 
That way ot won't brake anything for others users.

For UHS500 users, they will jave to change it on the switcher's menu to 60040 instead of the factory default which is 62000.

**Comment by McHauge** [comment]
@nyok92 all the changes you have here, are they tested and has been confirmed to work on the UHS500?

**Comment by nyok92** [comment]
Hi @McHauge , No I didn't tested it but it should work, should..

**Pull request merged**
